### ISSUE TITLE
Invisible high CPU load on Yosemite when binding is enabled

### ISSUE THREAD

**Issue by bfred-it** [joshbernfeld/Transmission-Interface-Binder#2]
TIB is causing my MacBook (mid-2009, 17", Core 2 Duo) with Yosemite 10.10.1 to jump to an insane 70% on idle. 

The worst thing is that Activity Monitor doesn't show anything using that much power. I did see TIB very high in the "Energy" tab but I didn't think much of it.

I closed TIB after hours of _debugging the system_ and… tadaaa…
![CPU usage drop](https://cloud.githubusercontent.com/assets/1402241/5695826/d908db8c-9968-11e4-9b47-60b8d77b56d8.png)

**Comment by bfred-it** [comment]
I noticed that it was doing it on a newer MacBook too (2011, 13", i7), but it was less visible since the CPU is more powerful. 

Here you can see how the usage dropped when I **stop**ped the interface binding.

![newer MacBook CPU drop](https://cloud.githubusercontent.com/assets/1402241/5696204/699b7b80-997a-11e4-92c4-08df4ffdaf74.png)

**Comment by joshbernfeld** [comment]
Hmm thank you for you feedback. I could not appreciate it more. I will begin investigating and hopefully should have this fixed sooner than later. Until then hold tight.

**Comment by bfred-it** [comment]
I found the issue: `autokiller` and `is_closed`:

* If Transmission is closed when I press start, the loop in `autokiller` uses the CPU.
* If Transmission is open when I press start, the loop in `is_closed` uses the CPU.

The issue appears when TIB is started BUT the interface is not (VPN not connected).

**Comment by joshbernfeld** [comment]
This is very interesting. I am on 10.9 and I notice an extremely small CPU load difference when running TIB and when not. If you add a sleep .5 into those loops that may fix the problem.

**Comment by joshbernfeld** [comment]
Thanks bfred, I have gone ahead and included your contribution in the latest build!

**Comment by bfred-it** [comment]
No problem! Thank you for TIB!
