### ISSUE TITLE
Disconnecting from VPN interface: "Interface not found"

### ISSUE THREAD

**Issue by winterflags** [joshbernfeld/Transmission-Interface-Binder#9]
I'm connecting to a VPN interface (`utun1`) and set Transmission-Interface-Binder to monitor this interface. Transmission then quits and restarts.

However, when disconnecting from the VPN, the interface `utun1` seems to disappear (I can no longer see it using `ifconfig`). Transmission-Interface-Binder then says "Interface not found" (paraphrasing). So it would seem that if it can't find the interface it was monitoring, it will not quit the application.

Is my interpretation correct? Is there anything that can be done to fix this issue?

**Comment by joshbernfeld** [comment]
That behavior should be expected. All that matters is when the interface reappears transmission restarts. There is no need to quit the app because transmission will be bound to the IP of an interface that no longer exists and shouldn't be able to make any outgoing connections.
